### ISSUE TITLE
Complete Search Bar test (ID:0202)

### ISSUE THREAD

**Issue by ElliotW1999** [SE701ProjectGroup4/git-brunching#161] opened 2020-03-20 07:26 UTC
![image](https://user-images.githubusercontent.com/48418365/77143788-10ccc180-6ae9-11ea-9033-7feea39a0d06.png)

**Comment by NathanMills1** [comment] 2020-04-27 04:00
Search bar working as intended, all tests passing. Closing Issue.

**Closed by NathanMills1** 2020-04-27 04:00 UTC
Labels: good first issue, needs-review, testing
